name: C/C++ CI

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: O0
      run:
        make O0=1

    - name: O1
      run:
        make O1=1

    - name: O2
      run:
        make O2=1

    - name: O3
      run:
        make O3=1

    - name: Og
      run:
        make Og=1

    - name: Ofast
      run:
        make Ofast=1
