name: C/C++ CI

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: O0
      run:
        make LONG=1 O0=1

    - name: O1
      run:
        make LONG=1 O1=1

    - name: O2
      run:
        make LONG=1 O2=1

    - name: O3
      run:
        make LONG=1 O3=1

    - name: Og
      run:
        make LONG=1 Og=1

    - name: Ofast
      run:
        make LONG=1 Ofast=1
